# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./data:/var/lib/bazadannih
    environment:
      POSTGRES_PASSWORD: password