# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres:
    image: postgres:12-alpine
  ports:
    - 8080:8080
  volumes:
    - ./data:/var/lib/postgres
  environment:
    - POSTGRES_DB=db
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password